polaris_admins_active:
  - username: alice
    fullname: The Admin
    pubkey: "ssh-rsa pubkey"
  - username: bob
    fullname: The Other Admin
    pubkey: "ssh-rsa pubkey"

polaris_admins_removed:
  - mallory

polaris_docker_users:
  - alice
  - bob

polaris_tailscale_args: --login-server http://swarm-manager:18080
