polaris_admins_active:
  - username: alice
    fullname: The Admin
    pubkey: "ssh-rsa pubkey"
  - username: bob
    fullname: The Other Admin
    pubkey: "ssh-rsa pubkey"

polaris_admins_removed:
  - mallory

polaris_docker_users:
  - alice
  - bob

polaris_tailscale_args: --login-server http://swarm-manager:18080

polaris_traefik_log_level: ERROR
polaris_traefik_entrypoints:
    websecure:
      address: ":443"
    web:
      address: ":80"
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    dbExporter:
      address: ":9104"
