- name: Prepare the Multipass VMs
  hosts: all
  tasks:
  - name: Populate Apt's Cache with package definitions
    become: true
    ansible.builtin.apt:
      update_cache: true
    when: vm_created is defined and vm_created.changed
