image:
    tag: 11.2.2
primary:
    root_password: r00t_passw0rd
    port: 33301
replica:
    root_password: r00t_passw0rd
    replication_secret: r3plicati0n_s3cr3t
    port: 33302
primed_volumes:
    - name: database-alpha-init
      path: docker-entrypoint-initdb.d
      target: /docker-entrypoint-initdb.d
superusers:
- name: dbdb
  password: d33b33d00b33d00
databases:
    - name: picom
      users:
        - name: picom_adm
          password: pic0m_adm_passw0rd
          grants:
            - all
        - name: picom_user
          password: pic0m_user_passw0rd
          grants:
            - select
            - insert
            - update
            - delete
            - index
