server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: 'http://loki:3100/loki/api/v1/push'

scrape_configs:
- job_name: journal
  journal:
    json: false
    labels: {job: systemd-journal}
    max_age: 12h
    path: /var/log/journal
  relabel_configs:
  - source_labels: [__journal__systemd_unit]
    target_label: unit
- job_name: system
  pipeline_stages: null
  static_configs:
  - labels: {__path__: /var/log/syslog, job: syslog, polaris_inventory: local}
    targets: [localhost]

