command:
  - "--configFile=/etc/traefik/config.yaml"

volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /etc/traefik:/etc/traefik
  - /var/log/traefik:/var/log/traefik

hostname: traefik.local

deploy:
  placement:
    constraints:
    - node.role==manager
    - node.hostname==swarm-manager

ports:
- target: 80 # Traefik entrypoint: web
  published: 80
  protocol: tcp
  mode: host
- target: 443 # Traefik entrypoint: websecure
  published: 443
  protocol: tcp
  mode: host
- target: 18080 # Traefik entrypoint: headscale
  published: 18080
  protocol: tcp
  mode: host

# Dollar signs in the password must be doubled, use the following sed call
# echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
users:
  # "user" "password"
  - "user:$$apr1$$Rq.c/siQ$$uN8tavHTlrpaU7dqL9ySR1"
